# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'UI' do
  pod 'Just'

  target 'UITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIUITests' do
    inherit! :search_paths
    # Pods for testing
  end
	
end
